/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sculpture.glb --transform 
Files: sculpture.glb [27.44MB] > /Users/developer/Documents/modsen-ancient-pr/modsen-ancient/public/sculpture-transformed.glb [2.71MB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sculpture-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.42, 12.028, -1.111]} rotation={[-1.645, 0.049, 0.125]}>
        <mesh geometry={nodes.sculpture_1.geometry} material={materials.skin} />
        <mesh geometry={nodes.sculpture_2.geometry} material={materials.bottom} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} rotation={[0.461, 0.668, -0.615]} />
    </group>
  )
}

useGLTF.preload('/sculpture-transformed.glb')
