/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 snowflake.glb --transform 
Files: snowflake.glb [9.55MB] > /Users/developer/Documents/modsen-ancient-pr/modsen-ancient/public/snowflake-transformed.glb [1.19MB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/snowflake-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.snowflake.geometry} material={materials.skin} position={[0.103, -0.203, -0.021]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/snowflake-transformed.glb')
